# Generated by Django 4.1 on 2022-08-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_Roll', models.IntegerField()),
                ('Std_Name', models.CharField(max_length=40)),
                ('Std_Fnm', models.CharField(max_length=40)),
                ('Std_Email', models.EmailField(max_length=40)),
                ('Std_Course', models.CharField(max_length=40)),
                ('Std_Pn', models.IntegerField()),
            ],
        ),
    ]
